// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIfevrCvnrjBzq45I_7cpBTKmxDHockrE',
    appId: '1:39473364364:web:ae969703145e00c596aaa9',
    messagingSenderId: '39473364364',
    projectId: 'furits-hup',
    authDomain: 'furits-hup.firebaseapp.com',
    storageBucket: 'furits-hup.firebasestorage.app',
    measurementId: 'G-5DW8MCZM4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAePQeJ5lasE20LvFn0wH5lpv4sCeFvojw',
    appId: '1:39473364364:android:343493c07874c1cf96aaa9',
    messagingSenderId: '39473364364',
    projectId: 'furits-hup',
    storageBucket: 'furits-hup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlLTuxTR4DZLbMRgx8-b9So6l8na3SkFo',
    appId: '1:39473364364:ios:fc5c1dc5bc0f018796aaa9',
    messagingSenderId: '39473364364',
    projectId: 'furits-hup',
    storageBucket: 'furits-hup.firebasestorage.app',
    iosBundleId: 'com.example.fruitHup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlLTuxTR4DZLbMRgx8-b9So6l8na3SkFo',
    appId: '1:39473364364:ios:fc5c1dc5bc0f018796aaa9',
    messagingSenderId: '39473364364',
    projectId: 'furits-hup',
    storageBucket: 'furits-hup.firebasestorage.app',
    iosBundleId: 'com.example.fruitHup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIfevrCvnrjBzq45I_7cpBTKmxDHockrE',
    appId: '1:39473364364:web:9792eac1fb27dda696aaa9',
    messagingSenderId: '39473364364',
    projectId: 'furits-hup',
    authDomain: 'furits-hup.firebaseapp.com',
    storageBucket: 'furits-hup.firebasestorage.app',
    measurementId: 'G-PC6XST6KHM',
  );
}
